name: Reusable Workflow
on:
    workflow_call:
        inputs:
            artifact-name:
                description: The name of the artifact to download
                required: false
                default: dist
                type: string
        outputs:
            deployment-status:
                description: The status of the deployment
                value: ${{ jobs.deploy.outputs.outcome }}
        secrets:
            some-secrets:
                description: Some secrets to use in the workflow
                required: false

jobs:
    deploy:
        runs-on: ubuntu-latest
        outputs:
            outcome: ${{ steps.set-result.outputs.step-result }}
        steps:
            - name: Get build artifacts
              uses: actions/download-artifact@v7
              with:
                name: ${{ inputs.artifact-name }}
            - name: Output contents
              run: ls
            - name: Deploy to production
              run: echo "Deploying to production..."
            - name: Set deployment status
              id: set-result
              run: echo "::set-output name=step-result::'success'"